"use client";

import { useChat } from "@ai-sdk/react";
import { eventIteratorToStream } from "@orpc/server";
import { SparklesIcon } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { client } from "@/lib/orpc";
import { MessageResponse } from "../ai-elements/message";
import { Button } from "../ui/button";
import {
  Popover,
  PopoverContent,
  PopoverDescription,
  PopoverHeader,
  PopoverTitle,
  PopoverTrigger,
} from "../ui/popover";
import { Separator } from "../ui/separator";
import { Skeleton } from "../ui/skeleton";

interface ComposeButtonProps {
  content: string;
  onAccept?: (markdown: string) => void;
}

export function ComposeButton({ content, onAccept }: ComposeButtonProps) {
  const [open, setOpen] = useState(false);
  const contentRef = useRef(content);

  useEffect(() => {
    contentRef.current = content;
  }, [content]);

  const {
    messages,
    status,
    error,
    sendMessage,
    setMessages,
    stop,
    clearError,
  } = useChat({
    id: "compose-message",
    transport: {
      async sendMessages(options) {
        return eventIteratorToStream(
          await client.ai.compose.generate(
            {
              content: contentRef.current,
            },
            { signal: options.abortSignal }
          )
        );
      },
      reconnectToStream() {
        throw new Error("Unsupported");
      },
    },
  });

  const lastAssistant = messages.findLast((m) => m.role === "assistant"); // reponse from AI
  const composedText =
    lastAssistant?.parts
      .filter((p) => p.type === "text")
      .map((p) => p.text)
      .join("\n\n") ?? "";

  function handleOpenChange(open: boolean) {
    setOpen(open);

    if (open) {
      const hasAssistantMEssage = messages.some((m) => m.role === "assistant");
      if (hasAssistantMEssage || (status !== "ready" && status !== "error"))
        return;

      sendMessage({ text: "Rewrite" });
    } else {
      stop();
      clearError();
      setMessages([]);
    }
  }

  return (
    <Popover open={open} onOpenChange={handleOpenChange}>
      <PopoverTrigger asChild>
        <Button className="rounded-full" size="sm">
          <SparklesIcon className="size-4" /> Compose
        </Button>
      </PopoverTrigger>
      <PopoverContent align="end">
        <PopoverHeader>
          <PopoverTitle className="flex items-center justify-between">
            <h1>Compose Message</h1>
            {status === "streaming" && (
              <Button
                variant="destructive"
                onClick={() => {
                  stop();
                }}
                type="button"
                size="xs"
              >
                Stop
              </Button>
            )}
          </PopoverTitle>
          <PopoverDescription className="flex items-center justify-between">
            Generated by AI
          </PopoverDescription>
        </PopoverHeader>

        <Separator />

        <div className="p-2 max-h-80 overflow-y-auto">
          {error ? (
            <div>
              <p>{error.message}</p>
              <Button
                onClick={() => {
                  clearError();
                  setMessages([]);
                  sendMessage({ text: "Compose" });
                }}
                type="button"
                size="xs"
              >
                Retry
              </Button>
            </div>
          ) : composedText ? (
            <MessageResponse>{composedText}</MessageResponse>
          ) : status === "submitted" || status === "streaming" ? (
            <div className="space-y-2">
              <Skeleton className="h-4 w-3/4" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-5/6" />
            </div>
          ) : (
            <div className="text-muted-foreground text-sm">
              Click compose to generate
            </div>
          )}
        </div>

        <div className="flex items-center gap-3 justify-end">
          <Button
            onClick={() => {
              if (!composedText) return;
              onAccept?.(composedText);
              stop();
              clearError();
              setMessages([]);
              setOpen(false);
            }}
            disabled={!composedText}
            type="button"
            size="sm"
          >
            Save
          </Button>
          <Button
            onClick={() => {
              stop();
              clearError();
              setMessages([]);
              setOpen(false);
            }}
            type="button"
            size="sm"
            variant="outline"
          >
            Decline
          </Button>
        </div>
      </PopoverContent>
    </Popover>
  );
}
