"use client";

import { useChat } from "@ai-sdk/react";
import { eventIteratorToStream } from "@orpc/client";
import { SparklesIcon } from "lucide-react";
import { useState } from "react";
import { client } from "@/lib/orpc";
import { MessageResponse } from "../ai-elements/message";
import { Button } from "../ui/button";
import {
  Popover,
  PopoverContent,
  PopoverDescription,
  PopoverHeader,
  PopoverTitle,
  PopoverTrigger,
} from "../ui/popover";
import { Separator } from "../ui/separator";
import { Skeleton } from "../ui/skeleton";

export function SummarizeThreadPopover({ threadId }: { threadId: string }) {
  const [open, setOpen] = useState(false);

  const {
    messages,
    status,
    stop,
    error,
    clearError,
    sendMessage,
    setMessages,
  } = useChat({
    id: `generate-summary-${threadId}`,
    transport: {
      async sendMessages(options) {
        return eventIteratorToStream(
          await client.ai.threads.summary.generate(
            { threadId },
            { signal: options.abortSignal }
          )
        );
      },
      reconnectToStream() {
        throw new Error("Unsupported");
      },
    },
  });

  const lastAssistant = messages.findLast((m) => m.role === "assistant"); // reponse from AI
  const summary =
    lastAssistant?.parts
      .filter((p) => p.type === "text")
      .map((p) => p.text)
      .join("\n\n") ?? "";

  function handleSummaryClick(n: boolean) {
    setOpen(n);

    if (n) {
      const hasAssistantMEssage = messages.some((m) => m.role === "assistant");
      if (hasAssistantMEssage || (status !== "ready" && status !== "error"))
        return;

      sendMessage({ text: "Summarize" });
    } else {
      stop();
      clearError();
      setMessages([]);
    }
  }

  return (
    <Popover open={open} onOpenChange={handleSummaryClick}>
      <PopoverTrigger asChild>
        <Button className="rounded-full" size="sm">
          <SparklesIcon className="size-4" /> Summarize
        </Button>
      </PopoverTrigger>
      <PopoverContent align="end">
        <PopoverHeader>
          <PopoverTitle className="flex items-center justify-between">
            <h1>Summary of Thread</h1>
            {status === "streaming" && (
              <Button
                variant="destructive"
                onClick={() => {
                  stop();
                }}
                type="button"
                size="xs"
              >
                Stop
              </Button>
            )}
          </PopoverTitle>
          <PopoverDescription className="flex items-center justify-between">
            Generated by AI
          </PopoverDescription>
        </PopoverHeader>

        <Separator />

        <div className="p-2 max-h-80 overflow-y-auto">
          {error ? (
            <div>
              <p>{error.message}</p>
              <Button
                onClick={() => {
                  clearError();
                  setMessages([]);
                  sendMessage({ text: "Summarize" });
                }}
                type="button"
                size="xs"
              >
                Retry
              </Button>
            </div>
          ) : summary ? (
            <MessageResponse>{summary}</MessageResponse>
          ) : status === "submitted" || status === "streaming" ? (
            <div className="space-y-2">
              <Skeleton className="h-4 w-3/4" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-5/6" />
            </div>
          ) : (
            <div className="text-muted-foreground text-sm">
              Click summarize to generate
            </div>
          )}
        </div>
      </PopoverContent>
    </Popover>
  );
}
